export const tools = [
  {
    slug: 'date-converter',
    title: 'Date Converter',
    description: 'Convert between Bikram Sambat (BS) and Anno Domini (AD) calendar dates.',
    icon: '📅',
    color: 'from-orange-400 to-red-500',
    keywords: ['BS AD converter', 'Nepali date converter', 'Bikram Sambat'],
  },
  {
    slug: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate exact age in years, months, and days from your birth date.',
    icon: '🎂',
    color: 'from-pink-400 to-rose-500',
    keywords: ['age calculator Nepal', 'date of birth calculator'],
  },
  {
    slug: 'gpa-calculator',
    title: 'GPA & Percent Calculator',
    description: 'Convert GPA to percentage, percentage to GPA, and calculate semester GPA.',
    icon: '🎓',
    color: 'from-blue-400 to-indigo-500',
    keywords: ['GPA to percent Nepal', 'TU GPA calculator', 'Pokhara University GPA'],
  },
  {
    slug: 'land-converter',
    title: 'Land Unit Converter',
    description: 'Convert between Ropani, Aana, Paisa, Daam, Bigha, Kattha, and Dhur.',
    icon: '🗺️',
    color: 'from-green-400 to-emerald-500',
    keywords: ['Ropani Aana converter', 'Bigha Kattha converter', 'Nepal land units'],
  },
  {
    slug: 'nepse-calculator',
    title: 'NEPSE Profit/Loss',
    description: 'Calculate share profit or loss including broker commission, SEBON fee, and DP charges.',
    icon: '📈',
    color: 'from-yellow-400 to-amber-500',
    keywords: ['NEPSE calculator', 'share profit loss Nepal', 'stock market Nepal'],
  },
  {
    slug: 'salary-tax',
    title: 'Salary Tax Calculator',
    description: 'Calculate income tax on salary as per Nepal Income Tax Act with SSF deductions.',
    icon: '💼',
    color: 'from-violet-400 to-purple-500',
    keywords: ['Nepal salary tax', 'income tax calculator Nepal', 'IRD tax Nepal'],
  },
  {
    slug: 'vat-calculator',
    title: 'VAT Calculator',
    description: 'Add or remove 13% VAT from any amount as per Nepal Revenue Authority rules.',
    icon: '🧾',
    color: 'from-teal-400 to-cyan-500',
    keywords: ['VAT calculator Nepal', '13% VAT Nepal', 'Nepal VAT'],
  },
  {
    slug: 'gold-calculator',
    title: 'Gold Price Calculator',
    description: 'Calculate gold value in Tola, Gram, and Ratti at current or custom rates.',
    icon: '🥇',
    color: 'from-yellow-300 to-orange-400',
    keywords: ['gold price Nepal', 'Tola to gram gold', 'Nepal gold calculator'],
  },
  {
    slug: 'land-registry',
    title: 'Land Registry Verifier',
    description: 'Verify land ownership, check lalpurja details, and validate plot numbers by district.',
    icon: '🏛️',
    color: 'from-red-400 to-rose-600',
    keywords: ['lalpurja verify Nepal', 'land ownership check Nepal', 'jagga dharani Nepal'],
  },
  {
    slug: 'agri-prices',
    title: 'Agricultural Price Tracker',
    description: 'Daily vegetable, fruit, and grain prices from Kalimati and major bazaars across Nepal.',
    icon: '🌾',
    color: 'from-lime-400 to-green-600',
    keywords: ['Kalimati vegetable price today', 'Nepal agricultural price', 'tarkari mulo Nepal'],
  },
  {
    slug: 'remittance',
    title: 'Remittance Comparator',
    description: 'Compare live exchange rates and fees from Western Union, IME, Prabhu, Wise and more.',
    icon: '💸',
    color: 'from-cyan-400 to-blue-600',
    keywords: ['remittance Nepal compare', 'send money Nepal best rate', 'IME vs Western Union Nepal'],
  },
]