import {
  Calendar,
  Cake,
  GraduationCap,
  Map,
  TrendingUp,
  Briefcase,
  Receipt,
  Medal,
} from 'lucide-react'

export const tools = [
  {
    slug: 'date-converter',
    title: 'Date Converter',
    description: 'Convert between Bikram Sambat (BS) and Anno Domini (AD) calendar dates.',
    icon: Calendar,
    iconBg: 'bg-orange-100 dark:bg-orange-900/40',
    iconColor: 'text-orange-600 dark:text-orange-400',
    color: 'from-orange-400 to-red-500',
    keywords: ['BS AD converter', 'Nepali date converter', 'Bikram Sambat'],
  },
  {
    slug: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate exact age in years, months, and days from your birth date.',
    icon: Cake,
    iconBg: 'bg-pink-100 dark:bg-pink-900/40',
    iconColor: 'text-pink-600 dark:text-pink-400',
    color: 'from-pink-400 to-rose-500',
    keywords: ['age calculator Nepal', 'date of birth calculator'],
  },
  {
    slug: 'gpa-calculator',
    title: 'GPA & Percent Calculator',
    description: 'Convert GPA to percentage, percentage to GPA, and calculate semester GPA.',
    icon: GraduationCap,
    iconBg: 'bg-blue-100 dark:bg-blue-900/40',
    iconColor: 'text-blue-600 dark:text-blue-400',
    color: 'from-blue-400 to-indigo-500',
    keywords: ['GPA to percent Nepal', 'TU GPA calculator', 'Pokhara University GPA'],
  },
  {
    slug: 'land-converter',
    title: 'Land Unit Converter',
    description: 'Convert between Ropani, Aana, Paisa, Daam, Bigha, Kattha, and Dhur.',
    icon: Map,
    iconBg: 'bg-green-100 dark:bg-green-900/40',
    iconColor: 'text-green-600 dark:text-green-400',
    color: 'from-green-400 to-emerald-500',
    keywords: ['Ropani Aana converter', 'Bigha Kattha converter', 'Nepal land units'],
  },
  {
    slug: 'nepse-calculator',
    title: 'NEPSE Profit/Loss',
    description: 'Calculate share profit or loss including broker commission, SEBON fee, and DP charges.',
    icon: TrendingUp,
    iconBg: 'bg-yellow-100 dark:bg-yellow-900/40',
    iconColor: 'text-yellow-600 dark:text-yellow-400',
    color: 'from-yellow-400 to-amber-500',
    keywords: ['NEPSE calculator', 'share profit loss Nepal', 'stock market Nepal'],
  },
  {
    slug: 'salary-tax',
    title: 'Salary Tax Calculator',
    description: 'Calculate income tax on salary as per Nepal Income Tax Act with SSF deductions.',
    icon: Briefcase,
    iconBg: 'bg-purple-100 dark:bg-purple-900/40',
    iconColor: 'text-purple-600 dark:text-purple-400',
    color: 'from-violet-400 to-purple-500',
    keywords: ['Nepal salary tax', 'income tax calculator Nepal', 'IRD tax Nepal'],
  },
  {
    slug: 'vat-calculator',
    title: 'VAT Calculator',
    description: 'Add or remove 13% VAT from any amount as per Nepal Revenue Authority rules.',
    icon: Receipt,
    iconBg: 'bg-teal-100 dark:bg-teal-900/40',
    iconColor: 'text-teal-600 dark:text-teal-400',
    color: 'from-teal-400 to-cyan-500',
    keywords: ['VAT calculator Nepal', '13% VAT Nepal', 'Nepal VAT'],
  },
  {
    slug: 'gold-calculator',
    title: 'Gold Price Calculator',
    description: 'Calculate gold value in Tola, Gram, and Ratti at current or custom rates.',
    icon: Medal,
    iconBg: 'bg-amber-100 dark:bg-amber-900/40',
    iconColor: 'text-amber-600 dark:text-amber-400',
    color: 'from-yellow-300 to-orange-400',
    keywords: ['gold price Nepal', 'Tola to gram gold', 'Nepal gold calculator'],
  },
]